In [61]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [62]:
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"

In [67]:
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [68]:
"# 1. How many tables are there? : " f"i have {len(data)} tables"

'# 1. How many tables are there? : i have 9 tables'

In [93]:
# 2. What does each table represent?
df1 = pd.read_csv(data["customers"])
list(df1.columns)
df2 = pd.read_csv(data["geolocation"])
list(df2.columns)

['geolocation_zip_code_prefix',
 'geolocation_lat',
 'geolocation_lng',
 'geolocation_city',
 'geolocation_state']

In [100]:
# 2. What does each table represent?
all_table_columns = []
for every_table in data:
    every_column = pd.read_csv(data[every_table])
    all_table_columns.append(list(every_column.columns))
all_table_columns

[['customer_id',
  'customer_unique_id',
  'customer_zip_code_prefix',
  'customer_city',
  'customer_state'],
 ['geolocation_zip_code_prefix',
  'geolocation_lat',
  'geolocation_lng',
  'geolocation_city',
  'geolocation_state'],
 ['order_id',
  'customer_id',
  'order_status',
  'order_purchase_timestamp',
  'order_approved_at',
  'order_delivered_carrier_date',
  'order_delivered_customer_date',
  'order_estimated_delivery_date'],
 ['order_id',
  'order_item_id',
  'product_id',
  'seller_id',
  'shipping_limit_date',
  'price',
  'freight_value'],
 ['order_id',
  'payment_sequential',
  'payment_type',
  'payment_installments',
  'payment_value'],
 ['review_id',
  'order_id',
  'review_score',
  'review_comment_title',
  'review_comment_message',
  'review_creation_date',
  'review_answer_timestamp'],
 ['product_id',
  'product_category_name',
  'product_name_lenght',
  'product_description_lenght',
  'product_photos_qty',
  'product_weight_g',
  'product_length_cm',
  'product_height_cm',
  'product_width_cm'],
 ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'],
 ['product_category_name', 'product_category_name_english']]

In [159]:
df1 = pd.read_csv(data["customers"])
df1.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [251]:
list(df1.columns)

['customer_id',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state']

In [161]:
print(df1.columns.tolist())

['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [162]:
df1["customer_id"].is_unique

True

In [163]:
df1["customer_unique_id"].is_unique

False

In [165]:
df1["customer_id"].duplicated().sum()

np.int64(0)

In [ ]:
# Primary key---->it should satisfy both uniqueness(.is_unique) and not null(.isna() or .isnull() ) values

In [248]:
df1 = pd.read_csv(data["customers"])
for col in df1.columns:
    #print(col,df1[col].is_unique)
    
    print(
        col,
        "Unique:", df1[col].is_unique,
        "Nulls:", df1[col].isna().sum()
    )

customer_id Unique: True Nulls: 0
customer_unique_id Unique: False Nulls: 0
customer_zip_code_prefix Unique: False Nulls: 0
customer_city Unique: False Nulls: 0
customer_state Unique: False Nulls: 0

In [249]:
df1[["customer_id", "customer_unique_id"]]

                            customer_id                customer_unique_id
0      06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1      18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2      4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3      b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4      4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066
...                                 ...                               ...
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

[99441 rows x 2 columns]

In [244]:
df1[["customer_id","customer_unique_id"]].nunique()

customer_id           99441
customer_unique_id    96096
dtype: int64

In [245]:
df1["customer_id"].is_unique

True

In [246]:
df1["customer_unique_id"].is_unique

False

In [247]:
df1.groupby("customer_unique_id")["customer_id"].nunique().sort_values(ascending=False).head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
1b6c7548a2a1f9037c1fd3ddfed95f33     7
12f5d6e1cbf93dafd9dcc19095df0b3d     6
de34b16117594161a6a89c50b289d35a     6
63cfc61cee11cbe306bff5857d00bfe4     6
f0e310a6839dce9de1638e0fe5ab282a     6
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
Name: customer_id, dtype: int64

In [250]:
df1[df1["customer_unique_id"] == "47c1a3033b8b77b3ab6e109eb4d5fdf3"]

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
4653,aa4178995eb97c7a31f3133c5b244651,47c1a3033b8b77b3ab6e109eb4d5fdf3,6634,jandira,SP
29807,9be414fa82e43d3fa9cea3b3cc00eae0,47c1a3033b8b77b3ab6e109eb4d5fdf3,6634,jandira,SP
39998,57802b83580aed851828868d4f7a4917,47c1a3033b8b77b3ab6e109eb4d5fdf3,6634,jandira,SP
57237,61fc851ac2ccfe9254c67b210b69ad7f,47c1a3033b8b77b3ab6e109eb4d5fdf3,6634,jandira,SP
74934,5daf8c734e89f88e5305f9283e7ca135,47c1a3033b8b77b3ab6e109eb4d5fdf3,6634,jandira,SP
78818,880b4294c02c693bb9882858758995d5,47c1a3033b8b77b3ab6e109eb4d5fdf3,6624,jandira,SP

In [184]:
for col in df1.columns:
    print(col, df1[col].duplicated().sum())

customer_id 0
customer_unique_id 3345
customer_zip_code_prefix 84447
customer_city 95322
customer_state 99414

In [205]:
df2 = pd.read_csv(data["geolocation"])
for col in df2.columns:
    print(col,
        "Unique:", df2[col].is_unique,
        "Nulls:", df2[col].isna().sum()
    )

geolocation_zip_code_prefix Unique: False Nulls: 0
geolocation_lat Unique: False Nulls: 0
geolocation_lng Unique: False Nulls: 0
geolocation_city Unique: False Nulls: 0
geolocation_state Unique: False Nulls: 0

In [185]:
for col in df2.columns:
    print(col, df2[col].duplicated().sum())

geolocation_zip_code_prefix 981148
geolocation_lat 282803
geolocation_lng 282550
geolocation_city 992152
geolocation_state 1000136

In [206]:
df3 = pd.read_csv(data["orders"])
for col in df3.columns:
    print(col,
          "Unique:", df3[col].is_unique,
          "Nulls:", df3[col].isna().sum()
         )

order_id Unique: True Nulls: 0
customer_id Unique: True Nulls: 0
order_status Unique: False Nulls: 0
order_purchase_timestamp Unique: False Nulls: 0
order_approved_at Unique: False Nulls: 160
order_delivered_carrier_date Unique: False Nulls: 1783
order_delivered_customer_date Unique: False Nulls: 2965
order_estimated_delivery_date Unique: False Nulls: 0

In [186]:
for col in df3.columns:
    print(col, df3[col].duplicated().sum())

order_id 0
customer_id 0
order_status 99433
order_purchase_timestamp 566
order_approved_at 8707
order_delivered_carrier_date 18422
order_delivered_customer_date 3776
order_estimated_delivery_date 98982

In [209]:
df4 = pd.read_csv(data["items"])
for col in df4.columns:
    print(col,
        "Unique:", df4[col].is_unique,
        "Nulls:", df4[col].isna().sum()
    )

order_id Unique: False Nulls: 0
order_item_id Unique: False Nulls: 0
product_id Unique: False Nulls: 0
seller_id Unique: False Nulls: 0
shipping_limit_date Unique: False Nulls: 0
price Unique: False Nulls: 0
freight_value Unique: False Nulls: 0

In [187]:
for col in df4.columns:
    print(col, df4[col].duplicated().sum())

order_id 13984
order_item_id 112629
product_id 79699
seller_id 109555
shipping_limit_date 19332
price 106682
freight_value 105651

In [210]:
df5 = pd.read_csv(data["payments"])
for col in df5.columns:
    print(col,
        "Unique:", df5[col].is_unique,
        "Nulls:", df5[col].isna().sum()
    )

order_id Unique: False Nulls: 0
payment_sequential Unique: False Nulls: 0
payment_type Unique: False Nulls: 0
payment_installments Unique: False Nulls: 0
payment_value Unique: False Nulls: 0

In [188]:
for col in df5.columns:
    print(col, df5[col].duplicated().sum())

order_id 4446
payment_sequential 103857
payment_type 103881
payment_installments 103862
payment_value 74809

In [211]:
df6 = pd.read_csv(data["reviews"])
for col in df6.columns:
    print(col,
        "Unique:", df6[col].is_unique,
        "Nulls:", df6[col].isna().sum()
    )

review_id Unique: False Nulls: 0
order_id Unique: False Nulls: 0
review_score Unique: False Nulls: 0
review_comment_title Unique: False Nulls: 87656
review_comment_message Unique: False Nulls: 58247
review_creation_date Unique: False Nulls: 0
review_answer_timestamp Unique: False Nulls: 0

In [189]:
for col in df6.columns:
    print(col, df6[col].duplicated().sum())

review_id 814
order_id 551
review_score 99219
review_comment_title 94696
review_comment_message 63064
review_creation_date 98588
review_answer_timestamp 976

In [212]:
df7 = pd.read_csv(data["products"])
for col in df7.columns:
    print(col,
        "Unique:", df7[col].is_unique,
        "Nulls:", df7[col].isna().sum()
    )

product_id Unique: True Nulls: 0
product_category_name Unique: False Nulls: 610
product_name_lenght Unique: False Nulls: 610
product_description_lenght Unique: False Nulls: 610
product_photos_qty Unique: False Nulls: 610
product_weight_g Unique: False Nulls: 2
product_length_cm Unique: False Nulls: 2
product_height_cm Unique: False Nulls: 2
product_width_cm Unique: False Nulls: 2

In [190]:
for col in df7.columns:
    print(col, df7[col].duplicated().sum())

product_id 0
product_category_name 32877
product_name_lenght 32884
product_description_lenght 29990
product_photos_qty 32931
product_weight_g 30746
product_length_cm 32851
product_height_cm 32848
product_width_cm 32855

In [213]:
df8 = pd.read_csv(data["sellers"])
for col in df8.columns:
    print(col,
        "Unique:", df8[col].is_unique,
        "Nulls:", df8[col].isna().sum()
    )

seller_id Unique: True Nulls: 0
seller_zip_code_prefix Unique: False Nulls: 0
seller_city Unique: False Nulls: 0
seller_state Unique: False Nulls: 0

In [181]:
for col in df8.columns:
    print(col, df8[col].duplicated().sum())

seller_id 0
seller_zip_code_prefix 849
seller_city 2484
seller_state 3072

In [214]:
df9 = pd.read_csv(data["product_category_name_translation"])
for col in df9.columns:
    print(col,
        "Unique:", df9[col].is_unique,
        "Nulls:", df9[col].isna().sum()
    )

product_category_name Unique: True Nulls: 0
product_category_name_english Unique: True Nulls: 0

In [180]:
for col in df9.columns:
    print(col, df9[col].duplicated().sum())

product_category_name 0
product_category_name_english 0

In [215]:
#  here we found whether the columns are unique or it has null values or not
#  if both conditions satisfy then it's satisfy the primary key condition.

In [144]:
# 3. How many rows are in each table?
# 4. How many columns are in each table?
# f"in customers table we have {df.shape} rows X columns are there"

In [145]:
pd.read_csv(data["customers"]).shape

(99441, 5)

In [146]:
pd.read_csv(data["geolocation"]).shape

(1000163, 5)

In [147]:
pd.read_csv(data["orders"]).shape

(99441, 8)

In [148]:
pd.read_csv(data["items"]).shape

(112650, 7)

In [149]:
pd.read_csv(data["payments"]).shape

(103886, 5)

In [150]:
pd.read_csv(data["reviews"]).shape

(99224, 7)

In [151]:
pd.read_csv(data["products"]).shape

(32951, 9)

In [152]:
pd.read_csv(data["sellers"]).shape

(3095, 4)

In [153]:
pd.read_csv(data["product_category_name_translation"]).shape

(71, 2)

In [ ]:
#  5. What are the primary keys?
# in customers table {customer_id }  --------->  Unique: True  and   Nulls: 0  -------------->   PK
# in orders table  {order_id}  --------------->  Unique: True  and   Nulls: 0  -------------->   PK
#                  {customer_id}  ------------>  Unique: True  and   Nulls: 0  -------------->   FK
# in products table{product_id}  ------------->  Unique: True  and   Nulls: 0  -------------->   PK
# in item table   {order_id}   --------------->  Unique: False and   Nulls: 0  ----------->     FK  b/c it connects items---->orders
#                 {order_item_id}------------->  Unique: False and   Nulls: 0  ------------>  FK b/c it connects items--->products

# in sellers table {seller_id}  -------------->  Unique: True  and   Nulls: 0  --->  PK
# in product_category_name_translation  ------> { product_category_name}      Unique: True   and  Nulls: 0
#                                          {product_category_name_english}    Unique: True   and  Nulls: 0

In [ ]:
# 5. What are the primary keys and foreign keys?

customers  -------------------->  customer_id → PK

orders  ---------------------->  order_id  → PK

       ----------------------->  customer_id → FK → customers.customer_id


products ----------------------> product_id  → PK


sellers  ---------------------->  seller_id  → PK

product_category_name_translation  -------------->  product_category_name
                                                 → Key used to connect to products.product_category_name
order_items
    (order_id, order_item_id)
    → Composite/natural key

    order_id
    → FK → orders.order_id

    product_id
    → FK → products.product_id

    seller_id
    → FK → sellers.seller_id

In [ ]:
# 6. Which columns connect the tables?
'Customers' + 'orders'      =  "customer_id"
'customers' + 'geolocation' = "ZIP prefix"
'sellers'   + 'items'       = "seller_id"
'sellers'   + 'geolocation' = "zip_prefix"
'products'  + 'items'       =  "product_id"
'products'  + 'product_category_name_translation' = "product_category_name"
'orders'    + 'items'       = "order_id"
'orders'    + 'reviews'     =  "order_id"
'payments'  +  'orders'     =  "order_id"

In [ ]:
# today what i did : Understand the olist dataset
# 1.loaded all datasets
# 2.check shape of the each dataset
# 3.check columns of each dataset
# 4.check it's duplicated, uniqueness and nullvalues there are not
# 5.identify the primary keys and foreign keys
# 6.also understand the table relationships