In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [270]:
def clean_data(orders,reviews,items):
    
    order_date_cols = ['order_purchase_timestamp',
                       'order_approved_at', 
                       'order_delivered_carrier_date',
                       'order_delivered_customer_date', 
                       'order_estimated_delivery_date']
    for col in order_date_cols:
        orders[col] = pd.to_datetime(orders[col])
    
    review_date_cols = ['review_creation_date',
                        'review_answer_timestamp']
    for col in review_date_cols:
        reviews[col] = pd.to_datetime(reviews[col])
    
    item_date_cols = ['shipping_limit_date']
    for col in item_date_cols:
        items[col] = pd.to_datetime(items[col])
    return (orders,reviews,items)

In [ ]:
# 21. Are there duplicate rows?
1.customers ----> we don't have any duplicates
2.geolocation ----> we have 261,831 duplicates
3.orders ----> we don't have any duplicates
4.items ----> we don't have any duplicates
5.payments ----> we don't have any duplicates 
6.reviews ----> we don't have any duplicates
7.products ----> we don't have any duplicates
8.sellers ----> we don't have any duplicates
9.product_category_name_translation ----> we don't have any duplicates

#  Geolocation contains 261,831 duplicate row occurrences, while the other Olist tables contain no exact duplicate rows based on df.duplicated().sum().

In [96]:
df1 = pd.read_csv(data["customers"])
df1.duplicated().sum()

np.int64(0)

In [97]:
df2

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [98]:
df2 = pd.read_csv(data["geolocation"])
df2.duplicated().sum()

np.int64(261831)

In [99]:
df2.shape[0]

1000163

In [100]:
df2["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [101]:
df2["geolocation_lat"].duplicated().sum()

np.int64(282803)

In [102]:
df2["geolocation_lng"].duplicated().sum()

np.int64(282550)

In [103]:
df2["geolocation_city"].duplicated().sum()

np.int64(992152)

In [104]:
df2["geolocation_state"].duplicated().sum()

np.int64(1000136)

In [148]:
duplicates = df2[df2.duplicated(keep=False)]
duplicates.sort_values(["geolocation_zip_code_prefix","geolocation_lat"],ascending=True).value_counts()
    #[(duplicates["geolocation_zip_code_prefix"] == 1046) & (duplicates["geolocation_lat"] == -23.546081) ]

geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  geolocation_city  geolocation_state
88220                        -27.102099       -48.629613       itapema           SC                   314
6414                         -23.495901       -46.874687       barueri           SP                   189
                             -23.490618       -46.869004       barueri           SP                   127
5145                         -23.506049       -46.717377       sao paulo         SP                   126
22620                        -23.005514       -43.375964       rio de janeiro    RJ                   102
                                                                                                     ...
20720                        -22.911518       -43.288969       rio de janeiro    RJ                     2
20715                        -22.908708       -43.270064       rio de janeiro    RJ                     2
                             -22.912357       -43.270797       rio de janeiro    RJ                     2
                             -22.912505       -43.271769       rio de janeiro    RJ                     2
99980                        -28.386689       -51.847091       david canabarro   RS                     2
Name: count, Length: 128174, dtype: int64

In [ ]:
duplicates.["geolocation_zip_code_prefix","geolocation_lat"],ascending=True).value_counts()
88220

In [153]:
df2[df2["geolocation_zip_code_prefix"] == 88220]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
908078,88220,-27.131977,-48.599234,itapema,SC
908079,88220,-27.102099,-48.629613,itapema,SC
908080,88220,-27.102099,-48.629613,itapema,SC
908081,88220,-27.102099,-48.629613,itapema,SC
908082,88220,-27.102099,-48.629613,itapema,SC
...,...,...,...,...,...
909277,88220,-27.102099,-48.629613,itapema,SC
909283,88220,-27.057344,-48.608344,itapema,SC
909286,88220,-27.102099,-48.629613,itapema,SC
909288,88220,-27.102099,-48.629613,itapema,SC
909289,88220,-27.099045,-48.615088,itapema,SC

In [149]:
duplicates[
    (duplicates["geolocation_zip_code_prefix"] == 88220 ) 
    #&
   # (duplicates["geolocation_lat"] == -23.546081)
]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
908079,88220,-27.102099,-48.629613,itapema,SC
908080,88220,-27.102099,-48.629613,itapema,SC
908081,88220,-27.102099,-48.629613,itapema,SC
908082,88220,-27.102099,-48.629613,itapema,SC
908092,88220,-27.102099,-48.629613,itapema,SC
...,...,...,...,...,...
909271,88220,-27.058449,-48.599532,itapema,SC
909277,88220,-27.102099,-48.629613,itapema,SC
909283,88220,-27.057344,-48.608344,itapema,SC
909286,88220,-27.102099,-48.629613,itapema,SC
909288,88220,-27.102099,-48.629613,itapema,SC

In [107]:
duplicates[(duplicates["geolocation_zip_code_prefix"] == 1046) ]

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
15,1046,-23.546081,-46.644820,sao paulo,SP
19,1046,-23.545884,-46.643163,sao paulo,SP
20,1046,-23.545166,-46.643786,sao paulo,SP
...,...,...,...,...,...
1412,1046,-23.545731,-46.643199,sao paulo,SP
1428,1046,-23.545731,-46.643199,sao paulo,SP
1432,1046,-23.545166,-46.643786,sao paulo,SP
1437,1046,-23.547191,-46.642923,sao paulo,SP
1457,1046,-23.545369,-46.643183,sao paulo,SP

In [108]:
duplicates[ (duplicates["geolocation_lat"] == -23.546081) ]

Empty DataFrame
Columns: [geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]
Index: []

In [109]:
df3 = pd.read_csv(data["orders"])
df3.duplicated().sum()

np.int64(0)

In [110]:
df4 = pd.read_csv(data["items"])
df4.duplicated().sum()

np.int64(0)

In [111]:
df5 = pd.read_csv(data["payments"])
df5.duplicated().sum()

np.int64(0)

In [112]:
df6 = pd.read_csv(data["reviews"])
df6.duplicated().sum()

np.int64(0)

In [113]:
df7 = pd.read_csv(data["products"])
df7.duplicated().sum()

np.int64(0)

In [114]:
df8 = pd.read_csv(data["sellers"])
df8.duplicated().sum()

np.int64(0)

In [115]:
df9 = pd.read_csv(data["product_category_name_translation"])
df9.duplicated().sum()

np.int64(0)

In [ ]:
# 22. Are there duplicate IDs?
1.customer ----> customer_id -->PK ----> no duplicates 
2.geolocation ----> we don't have any ID's
3.orders ----> order_id --> PK ----> no duplicates
        -----> customer_id --> FK ----> but no duplicates
4.items -----> 'order_id' --> FK ----> 13984 duplicate ID's
               'order_item_id' ----> UniqueKey ----> 112629 duplicate ID's
               'product_id' ----> FK ----> 79699 duplicate ID's
               'seller_id' ----> FK ----> 109555 duplicate ID's
5.payments ----> order_id ----> FK ----> 4446 duplicates ID's
6.reviews ----> review_id--->UniqueKey ----> 814 duplicates ID's
                order_id--->FK----->551 duplicate ID's
7.products ----> product_id --->PK ----> no duplicate ID's
8.sellers ---->seller_id -->PK ----> no duplicate ID's
9.product_category_translation ----> we don't have any ID's

In [116]:
df1["customer_id"].duplicated().sum()

np.int64(0)

In [117]:
df2

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [121]:
df3["order_id"].duplicated().sum()

np.int64(0)

In [125]:
df3["customer_id"].duplicated().sum()

np.int64(0)

In [140]:
df4["seller_id"].duplicated().sum()

np.int64(109555)

In [141]:
df4.seller_id.value_counts()

seller_id
6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
                                    ...
400f221ab83037c0ea78f1267da9624d       1
1746c1ae87ac63d530c7c943d0ac42e2       1
16bdc8cefd0e32a6f0824d296c5ad14a       1
ace601496e211a664100321f038f50af       1
13d95f0f6f73943d4ceffad0fc2cd32c       1
Name: count, Length: 3095, dtype: int64

In [159]:
df5["order_id"].duplicated().sum()

np.int64(4446)

In [172]:
df6["order_id"].duplicated().sum()

np.int64(551)

In [163]:
df6["review_id"].value_counts()

review_id
7b606b0d57b078384f0b58eac1d41d78    3
dbdf1ea31790c8ecfcc6750525661a9b    3
32415bbf6e341d5d517080a796f79b5c    3
0c76e7a547a531e7bf9f0b99cba071c1    3
4219a80ab469e3fc9901437b73da3f75    3
                                   ..
95e01591b0e69a2fab382b0c562d4e20    1
93611e0327d6a1769d1e68cf3caa242d    1
983c47de74278257f99c4b918fd380f1    1
ca475b77fcc618551ef9d516c3f61b88    1
efe49f1d6f951dd88b51e6ccd4cc548f    1
Name: count, Length: 98410, dtype: int64

In [171]:
df6

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [169]:
df6[df6["review_id"]=="7b606b0d57b078384f0b58eac1d41d78"]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
7500,7b606b0d57b078384f0b58eac1d41d78,f3028a8f41ea1ee2b461420913663f97,5,NaN,NaN,2017-02-15 00:00:00,2017-02-21 23:30:22
59859,7b606b0d57b078384f0b58eac1d41d78,2deb17060fc1ce18a85eba953ddcdeaf,5,NaN,NaN,2017-02-15 00:00:00,2017-02-21 23:30:22
61069,7b606b0d57b078384f0b58eac1d41d78,2f8f31eb2f7b6572836d662a6625c8e4,5,NaN,NaN,2017-02-15 00:00:00,2017-02-21 23:30:22

In [174]:
df7["product_id"].duplicated().sum()

np.int64(0)

In [178]:
df9

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [177]:
df8["seller_id"].duplicated().sum()

np.int64(0)

In [ ]:
# 23.Which columns need datetime conversion?
orders --> 'order_purchase_timestamp',
           'order_approved_at', 'order_delivered_carrier_date',
           'order_delivered_customer_date', 'order_estimated_delivery_date'
items ---> 'shipping_limit_date'     
reviews ---> 'review_creation_date',
             'review_answer_timestamp'
# these columns were stored in a non-datetime datatype so converted to datetime using pd.to_datetime():

In [185]:
df1.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [188]:
df2.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [206]:
df3.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                        object
order_delivered_carrier_date             object
order_delivered_customer_date            object
order_estimated_delivery_date            object
dtype: object

In [207]:
df3["order_purchase_timestamp"] = pd.to_datetime(df3["order_purchase_timestamp"])
df3["order_approved_at"] = pd.to_datetime(df3["order_approved_at"])
df3["order_delivered_carrier_date"] = pd.to_datetime(df3["order_delivered_carrier_date"])
df3["order_delivered_customer_date"] = pd.to_datetime(df3["order_delivered_customer_date"])
df3["order_estimated_delivery_date"] = pd.to_datetime(df3["order_estimated_delivery_date"])

In [208]:
df3.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [193]:
df4.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [214]:
df4["shipping_limit_date"] = pd.to_datetime(df4["shipping_limit_date"])
df4.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [195]:
df5.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [198]:
df6.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [216]:
df6["review_creation_date"] = pd.to_datetime(df6["review_creation_date"])
df6["review_answer_timestamp"] = pd.to_datetime(df6["review_answer_timestamp"])
df6.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [200]:
df7.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [202]:
df8.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [204]:
df9.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [ ]:
# 24.Are numerical columns stored correctly?
customer ---> customer_zip_code_prefix ->int64 ---> dont need conversion
geolocation ---> zip_code_prefix->int64,geolocation_lat,lng->float64 ---> dont need conversion
items --->order_item_id->int64,price,freight_value->float64 ---> dont need conversion
payments --->payment_sequential->int64,payment_installments->int64,payment_value->float64 ---> dont need conversion
reviews----> review_score->int 64 ---> dont need conversion
products ---> product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,
              product_length_cm,product_height_cm,product_width_cm ----> every column is float 64 ----> dont need conversion
sellers ----> seller_zip_code_prefix -> int64 ----> dont need conversion     

# All identified numerical columns are already stored in appropriate numeric datatypes (int64 or float64). 
# Therefore, no numerical datatype conversion is required at this stage.

In [ ]:
# 25.Are categorical columns stored correctly?
customers ---> customer_city,customer_state -> object
geolocation ---> geolocation_city,geolocation_state -> object
orders ---> order_status -> object
payments ---> payment_type -> object
reviews ---> review_comment_title,review_comment_message -> object
products ---> product_category_name -> object
sellers ---> seller_city,seller_state -> object
product_category_name_translation ---> product_category_name,product_category_name_english ---> object

# All identified categorical columns are stored as object, which is appropriate for the current analysis. 
# The review comment fields are free-text fields and are also appropriately stored as object. No datatype conversion is required at this stage.

In [223]:
df1.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [225]:
df1.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [227]:
df2.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [228]:
df2.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [229]:
df3.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [250]:
df3["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [230]:
df3.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [249]:
df3[
    df3["order_delivered_customer_date"] <
    df3["order_purchase_timestamp"]
]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [231]:
df4.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [232]:
df4.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [243]:
df4[["price","freight_value"]].min()

price            0.85
freight_value    0.00
dtype: float64

In [233]:
df5.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [234]:
df5.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [255]:
df5 = pd.read_csv(data["payments"])

In [266]:
df5["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [265]:
df5[df5["payment_type"] == "not_defined"]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [248]:
df5["payment_installments"].value_counts()

payment_installments
1     52546
2     12413
3     10461
4      7098
10     5328
5      5239
8      4268
6      3920
7      1626
9       644
12      133
15       74
18       27
11       23
24       18
20       17
13       16
14       15
17        8
16        5
21        3
0         2
22        1
23        1
Name: count, dtype: int64

In [247]:
df5["payment_installments"].max()

24

In [244]:
df5[["payment_installments","payment_value"]].min()

payment_installments    0.0
payment_value           0.0
dtype: float64

In [235]:
df6.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [236]:
df6.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [245]:
df6["review_score"].value_counts()

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

In [237]:
df7.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [238]:
df7.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [239]:
df8.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [240]:
df8.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [241]:
df9.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [242]:
df9.dtypes

product_category_name            object
product_category_name_english    object
dtype: object

In [ ]:
# 26. Are there suspicious values?
items--->  min values of ----> price 0.85,freight_value 0.00
payments ----> min values of ----> payment_installments 0.0,payment_value 0.0
        ----> but the payment_installments min is 0 and max is 24.here 0 is we need to analyse
        ----> in payment_type 3 records having not_defined payment method,voucher->6
reviews ----> review_score is between 1 to 5

#Most numerical values were within reasonable ranges. price has a minimum of 0.85 and freight_value has a minimum of 0, 
which are not necessarily suspicious. review_score ranges from 1 to 5 as expected. However, payment_installments contains a value of 0, 
which requires further investigation to understand whether it represents a valid business case or a data-quality issue.
# 9 payment records have a payment value of 0. Among them, 6 have payment type voucher and 3 have payment type not_defined. 
These records were flagged for further investigation rather than immediately being treated as errors.

In [261]:
df5["payment_installments"].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [262]:
df5[df5["payment_installments"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [267]:
df5[df5["payment_type"] == "not_defined"][
    ["order_id", "payment_type", "payment_installments", "payment_value"]
]

,order_id,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,not_defined,1,0.0

In [268]:
df5[df5["payment_value"] == 0][
    ["order_id", "payment_type", "payment_installments", "payment_value"]
]

,order_id,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,voucher,1,0.0

In [269]:
df5[df5["payment_value"] == 0]["payment_type"].value_counts()

payment_type
voucher        6
not_defined    3
Name: count, dtype: int64