In [ ]:
49. Which categories have the most orders?

50. Which categories generate the most revenue?

51. Which categories have the highest average order value?

52. Which categories have the highest average freight cost?

53. Which categories have the best review scores?

54. Which categories have the lowest review scores?

In [2]:
import pandas as pd
import os
import matplotlib.pyplot as plt
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [4]:
49. Which categories have the most orders?
i have product_id common in items,products tables.
so applied a merge on both tables using left join.
then applied groupby on product_category_name then performed count on order_id.
so i have more orders on this category cama_mesa_banho(bed_bath_table) and 9417 orders.

In [72]:
df_products=pd.read_csv(data["products"])
df_items=pd.read_csv(data["items"])
df_product_category_name_translation=pd.read_csv(data["product_category_name_translation"])

In [119]:
products_items = pd.merge(df_products,df_items,on="product_id",how="left")
x = products_items.groupby("product_category_name")["order_id"].nunique().sort_values(ascending=False)
pd.merge(x,df_product_category_name_translation,on="product_category_name",how="inner")

            product_category_name  order_id product_category_name_english
0                 cama_mesa_banho      9417                bed_bath_table
1                    beleza_saude      8836                 health_beauty
2                   esporte_lazer      7720                sports_leisure
3          informatica_acessorios      6689         computers_accessories
4                moveis_decoracao      6449               furniture_decor
..                            ...       ...                           ...
66             artes_e_artesanato        23         arts_and_craftmanship
67                     la_cuisine        13                    la_cuisine
68              cds_dvds_musicais        12             cds_dvds_musicals
69  fashion_roupa_infanto_juvenil         8     fashion_childrens_clothes
70             seguros_e_servicos         2         security_and_services

[71 rows x 3 columns]

In [92]:
x = df_products[df_products["product_category_name"] =="beleza_saude"]
y = x["product_id"].tolist()

In [96]:
df_items[df_items["product_id"].isin(y)]["price"].sum()

np.float64(1258681.3399999999)

In [ ]:
50. Which categories generate the most revenue?
Products -> Items -> both merge on product_id -> Category -> Sum of price(1258681.34)->category -> healthy_beauty

In [118]:
1036988.68/11115

93.29632748538012

In [90]:
products_items = pd.merge(df_products,df_items,on="product_id",how="inner")
revenue_category = products_items.groupby("product_category_name")["price"].sum().sort_values(ascending=False)
pd.merge(revenue_category,df_product_category_name_translation,on="product_category_name",how="inner")

            product_category_name       price product_category_name_english
0                    beleza_saude  1258681.34                 health_beauty
1              relogios_presentes  1205005.68                 watches_gifts
2                 cama_mesa_banho  1036988.68                bed_bath_table
3                   esporte_lazer   988048.97                sports_leisure
4          informatica_acessorios   911954.32         computers_accessories
..                            ...         ...                           ...
66                         flores     1110.04                       flowers
67                casa_conforto_2      760.27                home_comfort_2
68              cds_dvds_musicais      730.00             cds_dvds_musicals
69  fashion_roupa_infanto_juvenil      569.85     fashion_childrens_clothes
70             seguros_e_servicos      283.29         security_and_services

[71 rows x 3 columns]

In [ ]:
51. Which categories have the highest average order value?

Average order value → first calculate total value per order, then calculate the average of those order values.

In [209]:
products_items = pd.merge(
    df_products,
    df_items,
    on="product_id",
    how="inner"
)

order_value_category = (
    products_items
    .groupby(["product_category_name", "order_id"])["price"]
    .sum()
    .reset_index(name="order_value")
)

average_order_value_category = (
    order_value_category
    .groupby("product_category_name")["order_value"]
    .mean()
    .sort_values(ascending=False)
)

average_order_value_category

product_category_name
pcs                            1231.840497
portateis_casa_forno_e_cafe     632.609467
eletrodomesticos_2              484.263846
agro_industria_e_comercio       398.519066
instrumentos_musicais           304.934522
                                  ...
eletronicos                      62.841859
cds_dvds_musicais                60.833333
fraldas_higiene                  58.058889
flores                           38.277241
casa_conforto_2                  31.677917
Name: order_value, Length: 73, dtype: float64

In [ ]:
52. Which categories have the highest average freight cost?

“I merged the products and items tables using product_id, grouped the data by product category, 
calculated the average freight value for each category, 
and sorted the results in descending order to identify the categories with the highest average freight cost.”

In [206]:
products_items = pd.merge(df_products,df_items,on="product_id",how="inner").groupby("product_category_name")["freight_value"].mean().sort_values(ascending=False)
products_items

product_category_name
pcs                                               48.454680
eletrodomesticos_2                                44.538571
moveis_colchao_e_estofado                         42.906842
moveis_cozinha_area_de_servico_jantar_e_jardim    42.702598
moveis_quarto                                     42.497523
                                                    ...
alimentos                                         14.256922
casa_conforto_2                                   13.677000
fashion_roupa_feminina                            12.953125
livros_importados                                 12.830833
fashion_roupa_infanto_juvenil                     11.938750
Name: freight_value, Length: 73, dtype: float64

In [145]:
53. Which categories have the best review scores?
Merged items with products
Merged with reviews
Grouped by product_category_name
Calculated the average review score using .mean()
Sorted ascending to False get the highest scores first
Merged with the English category translation
cds_dvds_musicals ----------------> 4.642857 using round(2) -------> 4.64

In [173]:
df_reviews = pd.read_csv(data["reviews"])
df_product_category_name_translation = pd.read_csv(data["product_category_name_translation"])
items_products = pd.merge(df_items,df_products,on="product_id",how="inner")
items_products_reviews = pd.merge(items_products,df_reviews,on="order_id",how="inner")
avg_review_score = items_products_reviews.groupby("product_category_name")["review_score"].mean().sort_values(ascending=False).reset_index(name="average_score")
#pd.merge(max_review_score,df_product_category_name_translation,on="product_category_name",how="inner")
print("average maximum product category score:",avg_review_score.iloc[0,0],"with",avg_review_score.iloc[0,1],"maximum score")
print("average minimum product category score:",avg_review_score.iloc[-1,0],"with",avg_review_score.iloc[-1,1],"minimum score")

average maximum product category score: cds_dvds_musicais with 4.642857142857143 maximum score
average minimum product category score: seguros_e_servicos with 2.5 minimum score

In [170]:
avg_review_score

                            product_category_name  average_score
0                               cds_dvds_musicais       4.642857
1                   fashion_roupa_infanto_juvenil       4.500000
2                          livros_interesse_geral       4.446266
3              construcao_ferramentas_ferramentas       4.444444
4                                          flores       4.419355
..                                            ...            ...
68                              moveis_escritorio       3.493183
69                                       pc_gamer       3.333333
70  portateis_cozinha_e_preparadores_de_alimentos       3.266667
71                                fraldas_higiene       3.256410
72                             seguros_e_servicos       2.500000

[73 rows x 2 columns]

In [ ]:
54. Which categories have the lowest review scores?

Merged items with products
Merged with reviews
Grouped by product_category_name
Calculated the average review score using .mean()
Sorted ascending to get the lowest scores first
Merged with the English category translation
security_and_services ---------------------> 2.500000 using round(2) ------> 2.50

In [165]:
items_products = pd.merge(df_items,df_products,on="product_id",how="inner")
items_products_reviews = pd.merge(items_products,df_reviews,on="order_id",how="inner")
min_review_score = items_products_reviews.groupby("product_category_name")["review_score"].mean().sort_values(ascending=True).round(2)
pd.merge(min_review_score,df_product_category_name_translation,on="product_category_name",how="inner")
#min_review_score

,product_category_name,review_score,product_category_name_english
0,seguros_e_servicos,2.50,security_and_services
1,fraldas_higiene,3.26,diapers_and_hygiene
2,moveis_escritorio,3.49,office_furniture
3,casa_conforto_2,3.63,home_comfort_2
4,fashion_roupa_masculina,3.64,fashion_male_clothing
...,...,...,...
66,flores,4.42,flowers
67,construcao_ferramentas_ferramentas,4.44,costruction_tools_tools
68,livros_interesse_geral,4.45,books_general_interest
69,fashion_roupa_infanto_juvenil,4.50,fashion_childrens_clothes
70,cds_dvds_musicais,4.64,cds_dvds_musicals