In [ ]:
60. Which sellers have the most orders?

61. Which sellers generate the most revenue?

62. What is the average order value by seller?

63. Which sellers have higher review scores?

64. Which sellers have higher freight costs?

Don't just produce a "Top 10" list—explain what the result means.

In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
folder_path = "C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data"
data = {}
for file in os.listdir(folder_path):
    # print(file.split(".")[0])
    data[file.split(".")[0].replace("olist_","").replace("_dataset","").replace("order_","")] = folder_path + "/" + file
data

{'customers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_customers_dataset.csv',
 'geolocation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_geolocation_dataset.csv',
 'orders': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_orders_dataset.csv',
 'items': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_items_dataset.csv',
 'payments': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_payments_dataset.csv',
 'reviews': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_order_reviews_dataset.csv',
 'products': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_products_dataset.csv',
 'sellers': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/olist_sellers_dataset.csv',
 'product_category_name_translation': 'C:/Users/nagal/OneDrive/Documents/Learn/Repo/Olist-Project/data/product_category_name_translation.csv'}

In [ ]:
60. Which sellers have the most orders?

I grouped the data by seller_id and counted the unique order_ids for each seller. 
Then, I sorted the results in descending order to identify the sellers with the most orders.
    seller_id = "6560211a19b47992c3666cc44a7e94c0" , number of orders = "1854",seller_city = sao paulo,state = SP.

In [13]:
df_sellers = pd.read_csv(data["sellers"])
df_orders = pd.read_csv(data["orders"])
df_items = pd.read_csv(data["items"])

In [40]:
total_orders = df_items.groupby("seller_id")["order_id"].nunique().sort_values(ascending=False).reset_index(name="total_order_count")

In [41]:
df_sellers[df_sellers["seller_id"] == "6560211a19b47992c3666cc44a7e94c0"]

,seller_id,seller_zip_code_prefix,seller_city,seller_state
797,6560211a19b47992c3666cc44a7e94c0,5849,sao paulo,SP

In [ ]:
61. Which sellers generate the most revenue?
I grouped the data by seller ID and calculated the total revenue by summing the price for each seller. 
Then I sorted the results in descending order to identify the seller generating the most revenue.
seller_id = "4869f7a5dfa277a7dca6462dcf3b52b2",total_revenue = 229472.63,city = guariba, state = SP

In [39]:
df_sellers[df_sellers["seller_id"] == "4869f7a5dfa277a7dca6462dcf3b52b2"]

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2617,4869f7a5dfa277a7dca6462dcf3b52b2,14840,guariba,SP

In [38]:
df_items.groupby("seller_id")["price"].sum().sort_values(ascending=False).reset_index(name="total_revenue")

                             seller_id  total_revenue
0     4869f7a5dfa277a7dca6462dcf3b52b2      229472.63
1     53243585a1d6dc2643021fd1853d8905      222776.05
2     4a3ca9315b744ce9f8e9374361493884      200472.92
3     fa1c13f2614d7b5c4749cbc52fecda94      194042.03
4     7c67e1448b00f6e969d365cea6b010ab      187923.89
...                                ...            ...
3090  34aefe746cd81b7f3b23253ea28bef39           8.00
3091  702835e4b785b67a084280efca355756           7.60
3092  1fa2d3def6adfa70e58c276bb64fe5bb           6.90
3093  77128dec4bec4878c37ab7d6169d6f26           6.50
3094  cf6f6bc4df3999b9c6440f124fb2f687           3.50

[3095 rows x 2 columns]

In [ ]:
62. What is the average order value by seller?
First, I grouped by seller ID and order ID and summed the item prices to calculate the value of each order. 
Then I grouped by seller ID and calculated the mean of those order values to get the average order value for each seller. 
    Finally, I sorted the results in descending order.”

In [82]:
df_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [98]:
df_seller_order_value_sum = df_items.groupby(["seller_id","order_id"])["price"].sum().reset_index(name="price_sum").sort_values("price_sum",ascending=False)
df_seller_order_value_sum.groupby("seller_id")["price_sum"].mean().sort_values(ascending=False)

seller_id
80ceebb4ee9b31afb6c6a916a574a1e2    6729.00
ee27a8f15b1dded4d213a468ba4eb391    6499.00
b37c4c02bda3161a7546a4e6d222d5b2    6018.75
585175ec331ea177fa47199e39a6170a    3549.00
abe021b01ba992245271b9aa422032df    3360.00
                                     ...
702835e4b785b67a084280efca355756       7.60
1fa2d3def6adfa70e58c276bb64fe5bb       6.90
77128dec4bec4878c37ab7d6169d6f26       6.50
3d62f86afa7c73be2628a3be1423f5a0       6.00
cf6f6bc4df3999b9c6440f124fb2f687       3.50
Name: price_sum, Length: 3095, dtype: float64

In [ ]:
63. Which sellers have higher review scores?
I merged the reviews and items tables using order ID. 
Then I grouped the data by seller and calculated both the average review score and review count. 
I filtered out sellers with fewer than 50 reviews to make the comparison more strong, 
and finally sorted the sellers by average review score in descending order.

    seller_id = "d9bd94811c3338dceb4181f3dbc0c73e",review_mean = 4.819672, count = 61,city = sao paulo,state=SP

In [104]:
df_reviews = pd.read_csv(data["reviews"])
reviews_items = pd.merge(df_reviews,df_items,on="order_id",how="inner")
#score = reviews_items.groupby("seller_id")["review_score"].mean().sort_values(ascending=False).reset_index(name="review_score")
seller_score = (reviews_items.groupby("seller_id")["review_score"].agg(["mean", "count"]).reset_index())

seller_score = seller_score[seller_score["count"] >= 50].sort_values("mean", ascending=False)

In [105]:
seller_score

                             seller_id      mean  count
2624  d9bd94811c3338dceb4181f3dbc0c73e  4.819672     61
2526  d13e50eaa47b4cbe9eb81465865d8cfc  4.811594     69
1620  83e197e95a1bbabc8c75e883ed016c47  4.745455     55
2575  d566c37fa119d5e66c4e9052e83ee4ea  4.718310     71
646   376a891762bbdecbc02b4b6adec3fdda  4.672414     58
...                                ...       ...    ...
2000  a49928bcdf77c55c6d6e05e09a9b4ca5  2.952830    106
1029  54965bbe3e4f07ae045b90b0b8541f52  2.938272     81
1175  602044f2c16190c2c6e45eb35c2e21cb  2.932203     59
553   2eb70248d66e0e3ef83659f71b244378  2.712919    209
333   1ca7077d890b907f89be8c954a02686a  2.198529    136

[465 rows x 3 columns]

In [73]:
df_sellers[df_sellers["seller_id"] == "d9bd94811c3338dceb4181f3dbc0c73e"]

,seller_id,seller_zip_code_prefix,seller_city,seller_state
1169,d9bd94811c3338dceb4181f3dbc0c73e,4186,sao paulo,SP

In [ ]:
64. Which sellers have higher freight costs?
I grouped the items by seller ID and calculated the average freight value for each seller. 
Then I sorted the results in descending order to identify the sellers with higher average freight costs.
    seller_id = "6fa9202c10491e472dffd59a3e82b2a3",high_freight_cost = 308.336667,seller_city = sorocaba, state = SP

In [80]:
df_items.groupby("seller_id")["freight_value"].mean().sort_values(ascending=False)

seller_id
6fa9202c10491e472dffd59a3e82b2a3    308.336667
c88f62b4c386a59281014d677864d016    251.500000
ee27a8f15b1dded4d213a468ba4eb391    227.660000
80ceebb4ee9b31afb6c6a916a574a1e2    193.210000
56e361f411e38dcef17cdc2a3d99628b    185.776000
                                       ...
e9e446d01bd10a97a8ffcfc4a3a20cb2      7.390000
f0ec6a2adb05c62655a26dd347b8dede      7.390000
c97aa4ee7420f937da13b7f9e2228b99      6.660000
f664f98bfda2eaf266a23ff144e7a872      3.905000
0b36063d5818f81ccb94b54adfaebbf5      1.200000
Name: freight_value, Length: 3095, dtype: float64

In [81]:
df_sellers[df_sellers["seller_id"] == "6fa9202c10491e472dffd59a3e82b2a3"]

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2836,6fa9202c10491e472dffd59a3e82b2a3,18030,sorocaba,SP